# declare what image to use
# FROM image_name:latest
FROM python:3.13.4-slim-bullseye

# docker build -f Dockerfile -t pyapp .
# docker run -it pyapp

# docker build -f Dockerfile -t dockerdev1/ai-py-app-test:latest .
# docker run -it dockerdev/ai-py-app-test:latest
# docker push dockerdev1/ai-py-app-test:latest

# docker build -f Dockerfile -t pyapp .
# docker run -it -p 3000:8000 pyapp
# docker run -it -p 8000:8000 pyapp

# python -m http.server 8000
CMD ["python", "-m", "http.server", "8000"]

