# declare what image to use
# FROM image_name:latest
FROM python:3.13.4-slim-bullseye

# docker build -f Dockerfile -t pyapp .
# docker run -it pyapp

# docker build -f Dockerfile -t dockerdev1/ai-py-app-test:latest .
# docker run -it dockerdev/ai-py-app-test:latest
# docker push dockerdev1/ai-py-app-test:latest

